language: python
matrix:
  include:
    - python: 3.6
      env: TEST_MODE=PEP8
    - python: 3.6
      env: TF_VERSION1=1.4.0 TF_VERSION2=1.5.0
    - python: 3.6
      env: TF_VERSION1=1.6.0 TF_VERSION2=1.7.0
    - python: 3.6
      env: TF_VERSION1=1.8.0 TF_VERSION2=1.9.0
    - python: 3.6
      env: TF_VERSION1=1.10.0 TF_VERSION2=1.11.0
    - python: 3.6
      env: TF_VERSION1=1.12.0 TF_VERSION2=1.13.1
    - python: 3.6
      env: TF_VERSION1=1.14.0 TF_VERSION2=1.15.0
    - python: 3.6
      env: TF_VERSION1=2.0.0 TF_VERSION2=2.1.0
    - python: 3.6
      env: TF_VERSION1=2.2.0 TF_VERSION2=2.2.0
    - python: 2.7
      env: TF_VERSION1=1.4.0 TF_VERSION2=1.15.0
    - python: 2.7
      env: TF_VERSION1=2.0.0 TF_VERSION2=2.2.0
notifications:
  email: false
# Adapted from
# https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install --only-binary=numpy,scipy numpy scipy opencv-python cython pytest pytest-pep8

  - pip install .
  - export R=$(($RANDOM%2))
  - if [ $R -eq 0 ]; then
      export TF_VERSION=$TF_VERSION1;
    elif [ $R -eq 1 ]; then
      export TF_VERSION=$TF_VERSION2;
    fi
  - if [ -z "$TF_VERSION" ]; then
      pip install tensorflow==1.14.0;
    else
      pip install tensorflow==$TF_VERSION;
    fi

  # Ignore warnings
  - export TF16=$(python -c "from tensornets.utils import tf_later_than; print(tf_later_than('1.6.0'))")
  - if [[ $TF16 == "False" ]]; then
      echo 'filterwarnings =' >> pytest.ini;
      echo '    ignore::DeprecationWarning' >> pytest.ini;
      echo '    ignore::PendingDeprecationWarning' >> pytest.ini;
    fi

  # Detect whether core files are changed or not
  - export CORE_CHANGED=True;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "README.md" ]]; then export CORE_CHANGED=False; fi; done
  - export NUM_CHANGED=$(git diff --name-only HEAD~1 | wc -l);
  - if [ $NUM_CHANGED -gt 1 ]; then CORE_CHANGED=True; fi

  # Detect one of markdown files is changed or not
  - export DOC_ONLY_CHANGED=False;
  - if [ $NUM_CHANGED == 1 ] && [[ "$(git diff --name-only HEAD~1)" == *"md" ]]; then
      export DOC_ONLY_CHANGED=True;
    fi

script:
  - if [[ "$DOC_ONLY_CHANGED" == "False" ]]; then
      if [[ "$TEST_MODE" == "PEP8" ]]; then
         PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8;
      else
         PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --verbose --ignore=tests/all*;
      fi;
    fi
